name: GitHub Actions

on: [pull_request]

jobs:
    GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Linter
              run: npm run lint
            - name: Unit tests
              run: npm run test-coverage
            - name: Build app
              run: npm run build
