name: GitHub Actions

on: [pull_request]

jobs:
    GitHub-Actions:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Linter
              uses: npm run lint
            - name: Unit tests
              uses: npm run test-coverage
            - name: Build app
              uses: npm run build
